CREATE TABLE Books (
    book_id INT PRIMARY KEY,
    goodreads_book_id INT,
    best_book_id INT,
    work_id INT,
    books_count INT,
    isbn VARCHAR(20),
    isbn13 BIGINT,
    authors NVARCHAR(500),
    original_publication_year FLOAT,
    original_title NVARCHAR(255),
    title NVARCHAR(255),
    language_code NVARCHAR(10),
    average_rating FLOAT,
    ratings_count INT,
    work_ratings_count INT,
    work_text_reviews_count INT,
    ratings_1 INT,
    ratings_2 INT,
    ratings_3 INT,
    ratings_4 INT,
    ratings_5 INT,
    image_url NVARCHAR(2083),
    small_image_url NVARCHAR(2083)
);